
package org.dgac.ws.integration.server.alfresco.buscar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.dgac.ws.integration.server.alfresco.buscar.ObjectFactory;
import org.dgac.ws.integration.server.alfresco.buscar.ObtenerDocumentoRequest;
import org.dgac.ws.integration.server.alfresco.buscar.ObtenerDocumentoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ObtenerDocumentoPortType", targetNamespace = "http://soa.jboss.org/obtenerdocumento")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ObtenerDocumentoPortType {


    /**
     * 
     * @param in
     * @return
     *     returns cl.exe.obtenerdocumento.ObtenerDocumentoResponse
     * @throws ObtenerDocumentoFault1
     */
    @WebMethod(operationName = "ObtenerDocumentoOp", action = "http://soa.jboss.org/obtenerdocumento/ObtenerDocumentoOp")
    @WebResult(name = "obtenerDocumentoResponse", targetNamespace = "http://www.exe.cl/obtenerdocumento", partName = "out")
    public ObtenerDocumentoResponse obtenerDocumentoOp(
        @WebParam(name = "obtenerDocumentoRequest", targetNamespace = "http://www.exe.cl/obtenerdocumento", partName = "in")
        ObtenerDocumentoRequest in)
        throws ObtenerDocumentoFault1
    ;

}
