package org.dgac.ws.integration.client.alfresco.buscar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.dgac.ws.integration.server.alfresco.buscar.ObjectFactory;
import org.dgac.ws.integration.server.alfresco.buscar.ObtenerDocumentoRequest;
import org.dgac.ws.integration.server.alfresco.buscar.ObtenerDocumentoResponse;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsBuscarAlfrescoIF", targetNamespace = "http://soa.jboss.org/obtenerdocumento")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsBuscarAlfrescoIF {

	@WebMethod
    @WebResult(name = "ObtenerDocumentoResponse", partName = "ObtenerDocumentoResponse")
    public ObtenerDocumentoResponse ObtenerDocumentoOp(
        @WebParam(name = "ObtenerDocumentoRequest", partName = "ObtenerDocumentoRequest")
        ObtenerDocumentoRequest rq)
        throws Exception
    ;
}
