
package org.dgac.ws.integration.server.alfresco;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "almacenarDocumentosFault", targetNamespace = "http://www.exe.cl/almacenardocumentos")
public class AlmacenarDocumentosFault1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AlmacenarDocumentosFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AlmacenarDocumentosFault1(String message, AlmacenarDocumentosFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AlmacenarDocumentosFault1(String message, AlmacenarDocumentosFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.exe.almacenardocumentos.AlmacenarDocumentosFault
     */
    public AlmacenarDocumentosFault getFaultInfo() {
        return faultInfo;
    }

}
