
package org.dgac.ws.integration.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.dgac.ws.integration.server.LoginResponse;
import org.dgac.ws.integration.server.Login_Type;
import org.dgac.ws.integration.server.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSLoginIF", targetNamespace = "http://server.webservices.dgac.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSLoginIF {


    @WebMethod
    @WebResult(name = "LoginResponse", partName = "LoginResponse")
    public LoginResponse login(
        @WebParam(name = "Login", partName = "Login")
        Login_Type login)
        throws Exception
    ;
}
