package org.dgac.ws.integration.client.alfresco;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.dgac.ws.integration.server.ObjectFactory;
import org.dgac.ws.integration.server.alfresco.AlmacenarDocumentosRequest;
import org.dgac.ws.integration.server.alfresco.AlmacenarDocumentosResponse;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WsAlmacenarAlfrescoIF", targetNamespace = "http://soa.jboss.org/almacenardocumentos")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAlmacenarAlfrescoIF {

	@WebMethod
    @WebResult(name = "AlmacenarDocumentosResponse", partName = "AlmacenarDocumentosResponse")
    public AlmacenarDocumentosResponse AlmacenarDocumentosOp(
        @WebParam(name = "AlmacenarDocumentosRequest", partName = "AlmacenarDocumentosRequest")
        AlmacenarDocumentosRequest rq)
        throws Exception
    ;
}
